// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfeuqueyzjaxdvmzxkub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZXVxdWV5empheGR2bXp4a3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMTcyMjgsImV4cCI6MjA3NTg5MzIyOH0.sgf21GExWVIOjYwFyZuXrvoR0WSFMdHSHLI0fPu8skM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});